import { Router } from 'express';
import { RoomController } from '../controllers/RoomController';
import { RoomService } from '../services/RoomService';
import { roomRepository } from '../repositories';
import { authMiddleware, authorizeRoles } from '../middleware/auth.middleware';
import { validateBody, validateQuery } from '../middleware/validation.middleware';
import { CreateRoomSchema, UpdateRoomSchema, RoomFiltersSchema } from '../models/Room';
import { Role } from '@prisma/client';
const router = Router();
const roomService = new RoomService(roomRepository);
const roomController = new RoomController(roomService);
router.get('/', validateQuery(RoomFiltersSchema), (req, res) => roomController.getAllRooms(req, res));
router.get('/:id', (req, res) => roomController.getRoomById(req, res));
router.post('/', authMiddleware, authorizeRoles(Role.OWNER), validateBody(CreateRoomSchema), (req, res, next) => roomController.createRoom(req as any, res));
router.put('/:id', authMiddleware, authorizeRoles(Role.OWNER), validateBody(UpdateRoomSchema), (req, res, next) => roomController.updateRoom(req as any, res));
router.delete('/:id', authMiddleware, authorizeRoles(Role.OWNER), (req, res, next) => roomController.deleteRoom(req as any, res));
router.patch('/:id/status', authMiddleware, authorizeRoles(Role.OWNER), (req, res, next) => roomController.toggleRoomStatus(req as any, res));
export default router;